version: '3.1'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    image: app:latest
    secrets:
      - secret_key
      - admin_pword
      - admin_2fa

secrets:
  secret_key:
    file: secret_key
  admin_pword:
    file: admin_pword
  admin_2fa:
    file: admin_2fa
